version: "3"
services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    restart: unless-stopped
    # Use a seed so that our eth priv keys stay the same every time.
    command: ganache-cli --seed I_want_candy
    networks:
      - backend
  go-ipfs:
    image: ipfs/go-ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    restart: unless-stopped
    networks:
      - backend
  webapp:
    image: node:11
    volumes:
      - .:/usr/src/large
      - app_node_modules:/usr/src/large/node_modules
    working_dir: /usr/src/large
    command: bash -c "npm install && npm run docker-serve & npm run watch"
    ports:
      - "8081:8081"
    depends_on:
      - go-ipfs
      - ganache
    networks:
      - backend
    links:
      - "go-ipfs:ipfs"
networks:
  backend:
volumes:
  app_node_modules:
